### ISSUE TITLE
Feat(GI-TORM-Core): GI User data storage

### ISSUE THREAD

**Issue by Quantumlyy** [skyra-project/skyra#1080]
Implement a system for storing GI-related user data, such as gamer tags.

A data structure for FFXIV was already designed in S#.
https://github.com/skyra-project/skyra-sharp/blob/master/Skyra.Core/Database/Models/UserGameIntegrations.cs
https://github.com/skyra-project/skyra-sharp/blob/master/Skyra.Core/Database/Models/UserGameIntegrationsFFXIV.cs

**Comment by favna** [comment]
What exactly is the reason to do this? What is the end-goal / motivation?

**Comment by Quantumlyy** [comment]
You see in FFXIV for instance there are 2 types of accounts, Square Enix (SE) and FFXIV. With a paying subscription, you don't pay on the FFXIV account but on the SE account, which allows you to have 40 characters/FFXIV Accounts.
There's also the fact that one of my previous PRs added a `--server` flag which in its nature exposed that there can be conflicting names.
So when S# was still a thing Kyra and I settled on a system to store people's gamer tags, basing it off of the example that FFXIV presented.
This would then allow a user to store their 40 accounts and pick the desired one with just a number instead of the full name and server. It would also allow for us to use a default value if no name and server were provided.
Seeing as how we currently also have a CoC GI implementation we could store the player's tag for that as well and use it as a default value.

**Comment by favna** [comment]
Ah okay yeah sure that makes sense
