### ISSUE TITLE
request: make all i18n keys always return primitives

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#1178]
**Is your feature request related to a problem? Please describe.**

Needed for #1047, which will remove support for function and object based keys, as everything will return strings.

**Describe the solution you'd like**

Change everything to return a string, see examples below.

**Describe alternatives you've considered**

N/a.

**Additional context**

TODO:
- [ ] Functions to strings with interpolation

# Examples

<details><summary> expand to show already covered changes </summary>

## **object of strings (change key to be portable to json)**

These do not have to change as [i18next supports returning objects](https://www.i18next.com/translation-function/objects-and-arrays)

```ts
{
        COMMAND_ABILITY_DESCRIPTION: 'Gets data for any given Pokémon ability using my Pokémon dataset.',
        COMMAND_ABILITY_EMBED_DATA: {
            ABILITY: 'Ability',
            EXTERNAL_RESOURCES: 'External resources'
        }
}
```

to result in i18next json:
```jsonc
{
  // would move to `languages/en-US/commands.ts`
  "commands": {
    // ...
    "ability": {
      "description": "Gets data for any given Pokémon ability using my Pokémon dataset.",
      "author": "Ability" // check context -> in this case this was used for the setAuthor
      // ...
    }
    // ...
  },
  "system": {
    "pokemon": {
      "external_resources": "External resources"
    }
  }
}
```

## **Extended Description**

```ts
COMMAND_ABILITY_EXTENDED: builder.display('ability', {
	extendedHelp: 'Uses a fuzzy search to also match against near-matches.',
	explainedUsage: [
		['ability', 'The ability for which you want to find data']
	],
	examples: ['multiscale', 'pressure']
}),
```
becomes
```ts
{
	COMMAND_ABILITY_EXTENDED_DESCRIPTION: {
		EXTENDED_HELP: 'Uses a fuzzy search to also match against near-matches.',
		EXPLAINED_USAGE: [
			['ability', 'The ability for which you want to find data']
		],
		EXAMPLES: ['multiscale', 'pressure']
	}
}
```
to result in i18next json:
```jsonc
{
  // would move to `languages/en-US/commands.ts
  "commands": {
    // ...
    "ability": {
      "description": "Gets data for any given Pokémon ability using my Pokémon dataset.",
      "extendedDescription": {
        "name": "ability", // NOT optional
        "extendedHelp": "Uses a fuzzy search to also match against near-matches.", // optional
        "explainedUsage": [
          ["ability", "The ability for which you want to find data"]
        ],
        "possibleFormats": "", // optional
        "examples": ["multiscale", "pressure"], // optional
        "reminder": "", // optional
        "multiline": false // optional -> boolean value
      },
      "author": "Ability" // check context -> in this case this was used for the setAuthor
      // ...
    }
    // ...
  }
}
```

</details>

## **function that returns string should become just string**
*Note that this will also require modifying `Language#tget` to parse `{{ replacer }}` structures, as well as `message#sendLocale()` for the same change. (i.e. `message.sendTypedLocale` to match `tget`)

```ts
COMMAND_ABILITY_QUERY_FAIL: ability => `I am sorry, but that query failed. Are you sure \`${ability}\` is actually an ability in Pokémon?`,
```
becomes
```ts
COMMAND_ABILITY_QUERY_FAIL: 'I am sorry, but that query failed. Are you sure `{{ ability }}` is actually an ability in Pokémon?',
```
to result in i18next json:
```jsonc
{
  // would move to `languages/en-US/commands.ts`
  "commands": {
    // ...
    "ability": {
      "query_fail": "I am sorry, but that query failed. Are you sure `{{ ability }}` is actually an ability in Pokémon?"
      // ...
    }
    // ...
  }
}
```

<details> <summary> expand to show plurals, which is currently out of scope </summary>

## **plurals**

In the case of plurals, you can do
```ts
// ...
something: people => `There are ${people}!`,
people: number => `${number} person`,
people_plural: number => `${number} people`,
// ...
```

to result in i18next json:
```jsonc
{
  "something": "There are {{people}}",
  "people": "{{number}} person",
  "people_plural": "{{number}} people"
}
```
Which would be `t('commands:command.something', { people: t('commands:command.people', { number }) });`.
(Current code would be `language.get('commands.command.something', language.get(number === 1 ? 'commands.command.people' : 'commands.command.people_plural', number));`).

Later we can rewrite that to this:
```jsonc
{
  "something": "There are $t(people, {\"number\": {{number}} })",
  "people": "{{number}} person",
  "people_plural": "{{number}} people"
}
```
So we do `t('commands:command.something', { number });`

</details>

**Comment by Stitch07** [comment]
i18n keys are allowed to return objects, see: https://www.i18next.com/translation-function/objects-and-arrays

**Comment by favna** [comment]
Good catch, updated the issue.

**Comment by Stitch07** [comment]
And as a consequence, we can let EXTENDED_HELP return objects of strings instead of different keys.

**Comment by favna** [comment]
Updated that sample as well now
