### ISSUE TITLE
request: flatten i18n keys

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#1216]
**Is your feature request related to a problem? Please describe.**

We have some keys like the following:

```typescript
SOMETHING: {
	FOO: ({ count }) => `Foo ${count}`,
	BAR: ({ count }) => `Bar ${count}`,
	BAZ: ({ count }) => `Baz ${count}`
}
```

However, this won't translate well to i18next.

**Describe the solution you'd like**

Nevertheless it supports this

```json
{
	"something": {
		"foo": "Foo {{foos}}",
		"bar": "Bar {{bars}}",
		"baz": "Baz {{bazs}}"
	}
}
```

And based from the [official guides](https://www.i18next.com/translation-function/objects-and-arrays), we can specify `returnObjects: true`, which for the following example:

```json
{
    "tree": {
        "res": "added {{something}}"
    }
}
```

It can format its children keys:

```typescript
i18next.t('tree', { returnObjects: true, something: 'gold' });
// -> { res: 'added gold' }
```

So we need to change our code, since this is a step before the final transition, we should change the code above to:

```typescript
SOMETHING: ({ foos, bars, bazs }) => ({
	FOO: `Foo ${foos}`,
	BAR: `Bar ${bars}`,
	BAZ: `Baz ${bazs}`
})
```

This way the code calling the languages are the exact same in both versions, which is convenient.

**Describe alternatives you've considered**

Waiting for i18next and let the development cost be the same.

**Additional context**

https://www.i18next.com/translation-function/objects-and-arrays

**Comment by Favna** [comment]
A better solution is passing in an object then using `object.key` in each of the i18next keys. See https://www.i18next.com/translation-function/interpolation#working-with-data-models
