### ISSUE TITLE
request: make all i18n keys camelCase

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#1217]
**Is your feature request related to a problem? Please describe.**

Klasa's convention is to have all keys upper-case, however in i18next, the convention is to have them camelCase (with the occasional _snake for plural rules).

**Describe the solution you'd like**

Change all keys from SCREAMING_SNAKE_CASE to camelCase

**Describe alternatives you've considered**

1. Leaving it be? Feels weird to not follow the language standards.
1. Do this while we switch? Might increase development cost by a lot.

**Additional context**

N/a.

**Comment by favna** [comment]
Important: This also requires modifications to https://github.com/skyra-project/klasa and https://github.com/skyra-project/settings-gateway, which should be done close to merging so we don't get the wrong versions of the libs in development.
