### ISSUE TITLE
request: rework poll

### ISSUE THREAD

**Issue by favna** [skyra-project/skyra#1240]
**Is your feature request related to a problem? Please describe.**

The current `poll` command is more of a `vote` command. For a poll it would be good if it added numbers from 1 to 10, for each option given. Then rename the current `poll` to `vote`.

**Describe the solution you'd like**

IF amount of options <= 10 THEN use numbers (with a min of 1)
IF amount of options > 10 THEN use letters (with a max of 20 as that's max reactions)

**Describe alternatives you've considered**

N.A.

**Additional context**

N.A.

**Comment by Rexogamer** [comment]
thought max reactions was 20, not 23

**Comment by favna** [comment]
You're probably right, I wasn't sure
