### ISSUE TITLE
request: dehoist enhancements

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#1241]
**Is your feature request related to a problem? Please describe.**

The dehoist command is pretty simple and doesn't cover an edge case besides it has a bad UX:

- The command makes no exception for `'0'..='9'` characters (which are lower codepoints compared to `'A'`.
- The command doesn't say how many users is it renaming.
- The command doesn't include the progress (ratelimits make dehoist slow for +10 members), instead, it keeps in loading state.

**Describe the solution you'd like**

- [ ] Make exceptions for code points between `'0'` and `'9'`, inclusive.
- [ ] Edit the message with the number of hoisted members.
- [ ] Edit the message with the progress.
- [ ] (Optional) Rename while receiving packets from the gateway (and update accordingly), this allows Skyra to run dehoist on very large guilds.

**Describe alternatives you've considered**

N/a.

**Additional context**

N/a.

**Comment by cfanoulis** [comment]
Taking this for Hacktoberfest
