### ISSUE TITLE
request: switch to DiscordJS stable

### ISSUE THREAD

**Issue by favna** [skyra-project/skyra#1244]
**Is your feature request related to a problem? Please describe.**

In order to switch to Sapphire Framework we will need to upgrade to DiscordJS stable.

Among other things this means embracing managers.

**Describe the solution you'd like**

Upgrade the version then fix all the broken code

**Describe alternatives you've considered**

N.A.
~~klasa/core lmfaono~~

**Additional context**

N.A.

**Comment by kyranet** [comment]
Promoting this to `Priority: Critical` as bugs such as the one fixed on #1261 are starting to happen due to the lack of support for a lot of features, including security ones (`allowed_mentions`).
