### ISSUE TITLE
request: birthday commands

### ISSUE THREAD

**Issue by favna** [skyra-project/skyra#1339]
**Describe the solution you'd like**

We've had multiple requests for birthday related commands. They come down to 2 requests:

1. A command to wish a member a happy birthday with some random message: `s!birthday <member>`
2. A command to set reminders for whenever it is someone's birthday, which also automatically schedules a new reminder for the following year. Initially this can be done with user reminders but ideally it would be set up with guild reminders and require a "birthdays" channel where Skyra outputs the reminder to.

**Comment by Stitch07** [comment]
Might wanna add channel support for `remindme` while we're at it - i.e. `Skyra, remindme #general 2h something`.
