### ISSUE TITLE
refactor: only create audio queue once Lavalink connects

### ISSUE THREAD

**Issue by favna** [skyra-project/skyra#1354]
**Is your feature request related to a problem? Please describe.**

Right now, barring the changes made in https://github.com/skyra-project/skyra/pull/1352, it is required to run Redis with Skyra, even if `ENABLE_LAVALINK` is disabled. This isn't a really good developer experience.

**Describe the solution you'd like**

First of all, the changes from https://github.com/skyra-project/skyra/pull/1352 should be reverted. After that the proper solution should be implemented.

**Describe alternatives you've considered**

N.A.

**Additional context**

N.A.

**Comment by kyranet** [comment]
A fix for this has been included in #1681.
