### ISSUE TITLE
request: explore migration to mikro-orm

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#1371]
**Is your feature request related to a problem? Please describe.**

TypeORM is barely maintained, and gives us more issues than it fixes, to the point we're almost forced to resort to raw SQL queries.

**Describe the solution you'd like**

Explore whether or not Mikro-ORM is actually more stable than TypeORM and has all the features we need.

**Describe alternatives you've considered**

Ditching any existing ORM and making our own, not so ideal as that involves writing a codebase almost as large as Skyra's.

**Additional context**

N/a.

**Comment by kyranet** [comment]
After seeing @vladfrangu's public feedback, it is decided that Mikro-ORM may not be more stable than TypeORM, and its API seems to be confusing and inconsistent.

**Comment by vladfrangu** [comment]
API is *fine*, and, unless you use array columns, you'll probably be fine. I'd still recommend it, but honestly, you'd be better off using either Prisma, custom, or a different language

**Comment by kyranet** [comment]
The problem with Prisma is that it's nowhere comparable to Entity Framework, and would harm severely the eventual translation to .NET.
