### ISSUE TITLE
request: JumpTo should format in the language file

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#1372]
**Is your feature request related to a problem? Please describe.**

We repeat `JumpTo`'s code quite a few times and it's getting messier over time.

> Honestly, this pattern should be done in the translation string (so you end up with `language.get(JumpTo, { url })`

_Originally posted by @vladfrangu in https://github.com/skyra-project/skyra/pull/1301#discussion_r522409451_

**Describe the solution you'd like**

Format the entire string in the language files.

**Describe alternatives you've considered**

Keeping as-is?

**Additional context**

N/a.

**Comment by favna** [comment]
~~Please give this a proper title and dereference the issue as “this pattern”, instead just copy the pattern. We have issue templates for a reason.~~
