### ISSUE TITLE
request: make leaderboard paginated

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#1466]
**Is your feature request related to a problem? Please describe.**

The leaderboard command is something that can benefit a lot from being paginated, however, Klasa lacked of the support for lazy loaded pages.

| :warning: This issue depends on #1465's resolution. |
| --- |

**Describe the solution you'd like**

Make leaderboard use `LazyPaginatedMessage`.

**Describe alternatives you've considered**

Keeping it as-is.

**Additional context**

N/a.

**Comment by Rexogamer** [comment]
Fixed in #1719
