### ISSUE TITLE
feat: add Spectre.Console for all services.

### ISSUE THREAD

**Issue by Tylertron1998** [skyra-project/skyra#1595]
All our services are going to be displaying a *lot* of information. It would be nice if we could display that information in a non eyesore way - but how? *a new challenger approaches*

[Spectre.Console](https://spectresystems.github.io/spectre.console) is an awesome library for making pretty consoles, and helps by allowing to make the console into more of a 'UI' - one could imagine having logs on the left, stats on the right, important info in the middle, etc.

**Comment by kyranet** [comment]
The link is down, and this is more for Arkadia.
