### ISSUE TITLE
feature: few changes and new things requested

### ISSUE THREAD

**Issue by XynoxTheDev** [skyra-project/skyra#1631]
Heyo Guyz, 
I would like to suggest a few changes/updates in my beloved Skyra, which are mentioned below: 

### Leveling System

- [ ] The setup of the level-up reward roles should be made more user-friendly ie. the setup should be made easier to do as compared from now. Example: `skyra levelrole <level> <role:name/mention/id>`
  - Level input (`nL`, e.g. `10L`) has been added in #1667.
  - Parameter swap (similar to pay) is pending.
- [ ] Skyra should prompt the admin about setting the reward in the form of a stack or not ie. all reward roles should be assigned one after another else one is assigned and the previous one is removed.
- [x] No XP system should be enforced for roles that shouldn't get XP. Also, Skyra shouldn't give me a rewarding role if I have a blacklisted role. Also, there can be an option to increase or decrease the rate of XP gain. This feature can be limited to donators.
  - Ignored Roles (`social.ignored-roles`) have been added in #1668.
  - Multiplier (`social.multiplier`) has been added long ago in #728, and is a free feature.

### Suggestion System

There can be two different modes for suggestions:
- [ ] **Simple**: This mode will simply send the suggestion __without counting__ (`#123` and so on) them and __no feature for approving/denying them__.
- [ ] **Complex**: This mode will consist of the current suggestion system feature which Skyra is using right now ie. it shows the number of suggestions with the feature to approve/deny them.

### Music Player

- [ ] Instead of announcing each song playing in the current queue, Skyra can edit the message when there is no other message just after the song was announced previously. The reason for this suggestion is that it will reduce the spam (continuous new messages)* of song announcement.
  - Tracked at https://github.com/skyra-project/aelia/issues/342.
- [x] The whitelisting of voice channels wherein Skyra should play music, this thing should be in the form of an array.
  - Voice channel allow listing has been added in #1669.

### Moderation

- [ ] There should a toggle option for the mute command which whether to remove the roles before assigning the mute role or not.
  - https://github.com/skyra-project/skyra/issues/1335

### Miscellaneous

- [ ] Add a youtube notification system to notify users about the specified creator's upload/stream and other socials can also be added for the same thing.
  - Tracked at https://github.com/skyra-project/acrysel/issues/2
- [x] Add emoji command in Skyra just to add emojis from other servers.
  - `add-emoji` has been added in #1560.
- [x] Also add a flag for the categories, ie. Skyra will only show the commands of that specific category.
  Examples:
  Moderation: `skyra help --moderation`
  Admin:  `skyra help --admin`
  Music: `skyra help --music`
  - This already existed as `skyra help moderation`, `skyra help admin`, and `skyra help music`

**Thanks for reading and you might implement these changes/updates to Skyra someday. <3**

⭐ **Assets**
- Suggestion System:
  1. **Simple**:
     ![image](https://user-images.githubusercontent.com/51535331/110250616-3d9c1200-7fa2-11eb-9775-cc07030c443b.png)
  2. **Complex**:
     ![image](https://user-images.githubusercontent.com/51535331/110250654-6cb28380-7fa2-11eb-9408-18c0bd6babfc.png)
- Miscellaneous:
1. 
https://user-images.githubusercontent.com/51535331/110253052-485ca400-7fae-11eb-97cb-c8aa1988e156.mp4

**Comment by kyranet** [comment]
The suggestions section is moved to https://github.com/skyra-project/iriss. As for the simple/complex templates, we decided not to proceed with that since it changes one line. We'll make the complex one smaller and easier to read, though.

**Comment by kyranet** [comment]
All of the requests in this issue have been broken into smaller ones, links are added in the issue's body.
