### ISSUE TITLE
request: optional channel and role for birthday

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#1642]
**Is your feature request related to a problem? Please describe.**

The birthday system can give a role, however, at this moment, it must be configured so both the channel and the role are set up. There may be servers which might want a role to be given, but no announcement to be posted and vice versa.

**Describe the solution you'd like**

Make channel and role both optional (although require either if both were before).

**Describe alternatives you've considered**

N/a.

**Additional context**

N/a.

**Comment by Stitch07** [comment]
Closing because this already exists.

**Comment by kyranet** [comment]
Re-opening because that was not true.
https://github.com/skyra-project/skyra/blob/923f2cabaa2fa347dc327e355b484161d062b5e2/src/commands/Misc/Birthday/set-birthday.ts#L19-L25
