### ISSUE TITLE
Remove Excessive @

### ISSUE THREAD

**Issue by Skillz4Killz** [skyra-project/skyra#174]
The bot @ every time a song is played. This can get annoying if you want to repeat or listen to a queue and get @ every 2-4 minutes based on song length.

![image](https://user-images.githubusercontent.com/23035000/58722955-cc7c0380-83a6-11e9-8364-fd38c44e335b.png)

Curious: How do big bots like Rythm handle stuff like this?

**Comment by kyranet** [comment]
Rythm doesn't mention at all:
![image](https://user-images.githubusercontent.com/24852502/59145635-cc9f8300-89e6-11e9-87eb-91b67a8f3f1b.png)

Every bot has its own style, we could send the username instead of the mention, I don't know, but should be an easy fix.

**Comment by Tylertron1998** [comment]
I think using the displayName would be the best option - a really nice thing about Skyra is how "personal" she is - thus, a nickname (or falling back to the username) would be really nice.
