### ISSUE TITLE
bug: Song put on loop will "keep playing" long after the bot has been disconnected

### ISSUE THREAD

**Issue by superusercode** [skyra-project/skyra#1752]
**Describe the bug**

Song was played using the bot three days ago, put on repeat, and later the bot was disconnected (not sure if by itself or manually). Bot will still say it is looping the song every 12 hours or so, despite the song being only a couple minutes long.

**To Reproduce**

1. Queue a song
2. Loop the song
3. Disconnect bot manually or vacate the channel for auto disconnect, not sure what happened but I suspect former
4. Bot will post in channel saying song is looping still within 12-24 hours.

**Expected behavior**

The bot should not be ghost looping a song.

**Screenshots**

edit; still going

**Additional context**

**Comment by kyranet** [comment]
Fixed in #1787.
