### ISSUE TITLE
request(i18n): let user set personal language

### ISSUE THREAD

**Issue by Rexogamer** [skyra-project/skyra#1802]
**Is your feature request related to a problem? Please describe.**

If I'm in a server where Skyra's language is set to, say, German, I can't set my own language to override this - currently I would have to ask an admin to change it for everyone.

**Describe the solution you'd like**

I would like to be able to set a language exclusively for my account that would override any server-set languages.

**Describe alternatives you've considered**

None.

**Additional context**

This would be changed with a command (something like `setLanguage`) similar to `setColour`.

**Comment by kyranet** [comment]
This won't be needed with Discord's changes in i18n for slash commands, which will now send the user's and the guild's language.
