### ISSUE TITLE
request: Additional sub commands for some modules.

### ISSUE THREAD

**Issue by XynoxTheDev** [skyra-project/skyra#1811]
### AFK Command/Module

Add other sub commands to the AFK command or make AFK command a separate module.
- [x] **Ignored Channels:** a command to add channel as blacklisted.
- [x] **Allowed Role List:** only these roles can use the command other than mods.
- [x] **Reset:** to set yours/someone's AFK reason to default.
- [x] **Clear:** removes the AFK status of a member.
- [x] **List:** list of members who have set AFK status.

### Giveaway

- [x] End: command to end the ongoing giveaway whenever mods what to.

#### Thanks for reading and you might implement these changes/updates to Skyra someday. <3

**Comment by kyranet** [comment]
- **Allowed Role List:** only these roles can use the command other than mods.

This is already covered with permission nodes:

- `skyra pnode add everyone deny afk`
- `skyra pnode add my-allowed-role allow afk`
