### ISSUE TITLE
request: rewrite anime/manga to use AniList

### ISSUE THREAD

**Issue by favna** [skyra-project/skyra#1926]
**Is your feature request related to a problem? Please describe.**

Right now we're using Kitsu and need to show a lot of fields in the embed. The AniList API gives a nice splash image of the search result which will cut down the embed fields by a lot, greatly improving the command response.

**Describe the solution you'd like**

Migrate from Kitsu to AniList

**Describe alternatives you've considered**

- Stick with Kitsu

**Additional context**

API: https://github.com/AniList/ApiV2-GraphQL-Docs

**Comment by kyranet** [comment]
Fixed a long time ago with #1989
