### ISSUE TITLE
bug: TaskError method arguments are incorrect.

### ISSUE THREAD

**Issue by JABirchall** [skyra-project/skyra#1934]
**Describe the bug**

After writing a scheduled task, I noticed I was getting useless error output, after some time debugging I found that the arguments are being passed to TaskError in the wrong order. This causes TaskError its self to throw an error leading to misleading and unhelpful error messages after a ScheduledTask has thrown an error.

The TaskError run method expects `error: Error, context: TaskErrorPayload` parameters, but whats actually being passed are `entity: ScheduleEntity, task: UserTask, error: Error`

**To Reproduce**

1. Write a Scheduled task that will throw an error
2. Run the bot until the Scheduled task runs
3. See error

**Expected behavior**
The original Error from the Scheduled task should be output

**Screenshots**

![](https://i.imgur.com/Vph1hIU.png)

**Additional context**

**Comment by favna** [comment]
Thank you so much for finding this. Now to fix it... will you be picking this up yourself @JABirchall?

**Comment by JABirchall** [comment]
I only started developing ontop of skyra for a couple days, only really exposed myself to command and tasks ATM, I don't know enough about the project yet to attempting fixing the issue.
It would get fixed a lot faster by someone who knows their way around the project.
