### ISSUE TITLE
request: multiple welcome messages

### ISSUE THREAD

**Issue by Tylertron1998** [skyra-project/skyra#1936]
**Is your feature request related to a problem? Please describe.**

Currently, Skyra only supports a single, non changing welcome message.

The biggest issue with bot based welcome messages is how disingenuous it feels. However, being able to use multiple, randomly chosen welcome messages is a bit better, as it shows more thought and effort goes into it.

**Describe the solution you'd like**

Being able to set multiple, randomly chosen welcome messages.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by kyranet** [comment]
Since we are removing the welcome messages from Skyra, we will not proceed with the implementation of this feature.
