### ISSUE TITLE
request: set `allowedMentions` to accept the parameterized input for custom commands

### ISSUE THREAD

**Issue by favna** [skyra-project/skyra#1938]
**Is your feature request related to a problem? Please describe.**

Currently when using parameterized input like `{user}` in custom commands the message Skyra sends has `allowedMentions` set to not actually ping the targeted user. This should be changed.

**Describe the solution you'd like**

Setting the `allowedMentions` to match user input

**Describe alternatives you've considered**

N.A.

**Additional context**

`skyra bearhug {user}` in Skyra Dev should ping `{user}`

**Comment by SHIVA099** [comment]
I think the bot should ping the user..

**Comment by SHIVA099** [comment]
We add coustom commands for our needs.. so I guess pinging the target user should also be there..

**Comment by JABirchall** [comment]
Maybe if we add to the parameter if it should mention or not?

**Comment by Insidious092** [comment]
if there could be a separate placeholder {user.mention} for pinging purpose also the default one {user} can be kept as optional without ping.
