### ISSUE TITLE
bug: reaction roles do not work if Skyra is to assign a role higher than herself

### ISSUE THREAD

**Issue by favna** [skyra-project/skyra#1983]
**Describe the bug**

Skyra does not check role hierarchy when attempting to add a new role through reaction roles, causing a MISSING PERMISSION Discord error to be thrown to the console and no feedback being given to the user.

**To Reproduce**

1. Give Skyra full admin permissions, but put her role at the bottom of the list
2. Create a new role, above Skyra
3. Create a new reaction role bound to that new role
4. With an alt user try to claim the role
5. A permission error will be logged to the console

**Expected behavior**

An error gets thrown informing the server that they should put the Skyra role higher in the role hierarchy

**Screenshots**

![](https://i.imgur.com/06jloiL.png)

![](https://i.imgur.com/h4TUyVW.gif)

**Additional context**

Error log of a failed assignment:
```
skyra          | 2021-07-25T13:42:13.580937451Z 2021-07-25 13:42:13 - WARN  - [API ERROR] [CODE: 50013] Missing Permissions
skyra          | 2021-07-25T13:42:13.580985593Z 2021-07-25 13:42:13 - WARN  -             [PATH: patch /guilds/868176846389407784/members/268792781713965056]
skyra          | 2021-07-25T13:42:13.581046298Z 2021-07-25 13:42:13 - FATAL - DiscordAPIError: Missing Permissions
skyra          | 2021-07-25T13:42:13.581059914Z 2021-07-25 13:42:13 - FATAL -     at RequestHandler.execute (/usr/src/app/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
skyra          | 2021-07-25T13:42:13.581064684Z 2021-07-25 13:42:13 - FATAL -     at runMicrotasks (<anonymous>)
skyra          | 2021-07-25T13:42:13.581067890Z 2021-07-25 13:42:13 - FATAL -     at processTicksAndRejections (node:internal/process/task_queues:96:5)
skyra          | 2021-07-25T13:42:13.581071026Z 2021-07-25 13:42:13 - FATAL -     at async RequestHandler.push (/usr/src/app/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
skyra          | 2021-07-25T13:42:13.581074141Z 2021-07-25 13:42:13 - FATAL -     at async SkyraGuildMember.edit (/usr/src/app/node_modules/discord.js/src/structures/GuildMember.js:312:5)
skyra          | 2021-07-25T13:42:13.581077247Z 2021-07-25 13:42:13 - FATAL -     at async UserEvent.run (/usr/src/app/typescript/dist/events/reactions/rawReactionAddRole.js:31:13)
skyra          | 2021-07-25T13:42:13.581080624Z 2021-07-25 13:42:13 - FATAL -     at async UserEvent._run (/usr/src/app/node_modules/@sapphire/framework/dist/lib/structures/Event.js:78:13)
```

**Comment by lveneris** [comment]
Is this still an issue? If so, it's handled [here](https://github.com/skyra-project/skyra/blob/main/src/listeners/reactions/rawReactionAddRole.ts) right?

**Comment by kyranet** [comment]
Still an issue and it's handled there, yes.

**Comment by lveneris** [comment]
I'll work on this, then.

**Comment by lveneris** [comment]
I envision that might spam quite significantly if people react and unreact quickly. How should we tackle that? Send one message and after that remain silent?

**Comment by kyranet** [comment]
That's a separate issue 😅

**Comment by lveneris** [comment]
> That's a separate issue 😅

An important one, nonetheless. I'll just get it working for now, we can figure out the best way to notify them later.
