### ISSUE TITLE
request: tickets

### ISSUE THREAD

**Issue by JABirchall** [skyra-project/skyra#1993]
**Is your feature request related to a problem? Please describe.**
Simulator to how other frameworks do this. Eg: https://ticketsbot.net/
Ticket could be opened by reaction.

**Describe the solution you'd like**
An administrator can designate a message reaction to opening a tick.
When the reaction is clicked, a new ticket is created using discord new threads feature.
the user who reacted and moderator+ (discuss - could be separate support roles?) will have access the thread.
Within these channels, certain ticket commands can be used. such as close, archive etc

**Describe alternatives you've considered**
none

**Additional context**
New commands will need to be added.
!manage-ticket-reaction
!ticket <new|close|delete> 

- new - Creates a new ticker
- close - remove user access but keep the thread permanent, delete can be used at a later date.
- delete - delete the thread and all messages

!conf roles.support <add|remove|reset> @Role - Add new support roles?

Othere aspects may need to be discussed

**Comment by JABirchall** [comment]
This could also use the new button?

**Comment by favna** [comment]
Threads will also definitely help with this.

**Comment by favna** [comment]
Following our decisions for Skyra V7 and the removal of many of the complex and hard to maintain features we will not be implementing this and instead recommending users to use a bot like the aforementioned ticketsbot.net. 

You can read more about this upcoming version [here](https://skyra.notion.site/Skyra-v7-922ba06004654142a7b63347a92513a8)
