### ISSUE TITLE
request: replace related commands to sub-commands

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#1994]
**Is your feature request related to a problem? Please describe.**

Currently, Skyra has a total of 268 commands, however, Discord allows only 100 global slash commands, alongside an additional list of 100 per-guild slash commands.

**Describe the solution you'd like**

Similar to #1933, we need to cut down the command count by a factor of 2.67 (37%) by making them sub-commands, or dropping them entirely.

**Describe alternatives you've considered**

Do the cut-down in slashies only? De-synchronises the message-based and interaction-based commands, which can be bad.

**Additional context**

https://discord.com/developers/docs/interactions/slash-commands#a-quick-note-on-limits

**Comment by favna** [comment]
Seeing as we can apply for the new intent _and_ we have 9 months to make this change this is a far less pressing issue that it was originally written to be. Dropped priority to low.

**Comment by kyranet** [comment]
We have drafted a list of commands and subcommands, as well as trimmed them with the separation of Skyra into 9 single-purpose bots. This is not longer an issue and the [Notion document](https://skyra.notion.site/Skyra-v7-922ba06004654142a7b63347a92513a8) should be used instead.
