### ISSUE TITLE
bug: Validate Date - remind

### ISSUE THREAD

**Issue by JABirchall** [skyra-project/skyra#2002]
**Describe the bug**

remind allows for an arbitrary date outside the range specified by ISO_8601. This errors out on when sending to discord the embed with an invalid DateTime.

9999-12-31 - Acceptable
10000-01-01 - Not allowed While technically a valid date, ISO_8601 does not allow dates past year 9999

**To Reproduce**

Run command `s!remind 10000-01-01 Do you like this`
While this reminder will never be triggered, when requesting the reminder using `s!remind show {id}`
The datetime is invalid and discord refuses the request.

**Expected behavior**

Datetime should be validated against ISO_8601 where the year is no more than 4 digits in length

**Screenshots**

![](https://i.imgur.com/srhMrax.png)

**Additional context**

```
DiscordAPIError: Invalid Form Body
embed.timestamp: Could not parse +010000-08-22T00:00:00.000Z. Should be ISO8601.
embeds[0].timestamp: Could not parse +010000-08-22T00:00:00.000Z. Should be ISO8601.
    at RequestHandler.execute (/usr/src/app/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/usr/src/app/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async SkyraMessage.send (/usr/src/app/node_modules/@skyra/editable-commands/dist/index.js:1:1104)
    at async CoreEvent.run (/usr/src/app/node_modules/@sapphire/framework/dist/events/command-handler/CoreCommandAccepted.js:15:28)
    at async CoreEvent._run (/usr/src/app/node_modules/@sapphire/framework/dist/lib/structures/Event.js:78:13)
```

**Comment by Tylertron1998** [comment]
I'm not sure how I feel about this. Honestly, adding additional logic and checks to allow a Date outside the bounds of ISO8601 seems very much overkill; adding additional code complexity and overhead (and, ultimately, code debt) for a feature that won't be used in any serious fashion (no current user of Skyra will even be alive past 1000AD, let alone Skyra herself) seems like a bad idea.

**Comment by JABirchall** [comment]
> 
> 
> I'm not sure how I feel about this. Honestly, adding additional logic and checks to allow a Date outside the bounds of ISO8601 seems very much overkill; adding additional code complexity and overhead (and, ultimately, code debt) for a feature that won't be used in any serious fashion (no current user of Skyra will even be alive past 1000AD, let alone Skyra herself) seems like a bad idea.

While I agree with the added complexity comment, some date validation is already done. a user did submit a remindme with a date `102022-08-22` i feel like like some feedback about the requested date not being ISO_8601 valid to squash out mistaken input.
We could at least add a hardlimit for date year not being over a certain time in the future

**Comment by Tylertron1998** [comment]
I definitely agree that the error message is not as helpful as it should be - that's something that could be fixed fairly easily.

**Comment by kyranet** [comment]
Does this bug still happen today?

**Comment by JABirchall** [comment]
It is confirmed to still be a bug, yes.
