### ISSUE TITLE
fix(giveaway): help examples

### ISSUE THREAD

**Issue by XynoxTheDev** [skyra-project/skyra#2017]
Example for `gstart` command in the help command of that is wrong!

https://user-images.githubusercontent.com/51535331/131335741-2d5139ed-ea29-4348-8eb3-79ca83fb854f.mp4

**Comment by Bracciata** [comment]
I would like to tackle this one.

**Comment by Bracciata** [comment]
I would like to note it seems that just the help output is wrong because 2w as a number for winners does not make sense.
