### ISSUE TITLE
bug: send welcome message after member has passed membership screening

### ISSUE THREAD

**Issue by anishshobithps** [skyra-project/skyra#2025]
**Describe the bug**

Right now, Skyra sends a welcome message as soon as a user joins the server. But after the introduction of Membership Screening the user has to go through the rules then the user will be able to chat, Skyra doesn't check if member is still at the state of pending. It would make more sense to welcome a user after they are done with Membership Screening. 

**To Reproduce**

1) Enable system messages on discord server 
2) Enable Welcome messages
3) When a user joins the server, Skyra welcome's the user. 
4) If the user didn't complete membership Screening yet there is no system message sent. 
5) Once the user membership Screening is completed, system message is sent welcoming the user. 

**Expected behavior**

Skyra should send messages after the person has completed membership Screening

**Screenshots**

N/A

**Additional context**

There seems to be problem with the underlying library discord.js for this to work. 
https://github.com/discordjs/discord.js/issues/6546

**Comment by favna** [comment]
FYI Skyra is currently on DiscordJS v12 which doesn't even have the `guildmember.pending` property yet, regardless of whether it is true or not. We cannot fix this until we finish up the V13 update.

**Comment by kyranet** [comment]
Since we'll remove greetings from Skyra, following the [Notion document](https://skyra.notion.site/Skyra-v7-922ba06004654142a7b63347a92513a8), we will not proceed with this suggestion.
