### ISSUE TITLE
request: minecraft player skin command

### ISSUE THREAD

**Issue by Tylertron1998** [skyra-project/skyra#2175]
**Is your feature request related to a problem? Please describe.**

A command to get the skin of any minecraft player.

**Describe the solution you'd like**

s!mcskin <playername> [--tilt: number]

**Additional context**

First, the player name needs to be resolved into a UUID: `GET https://api.mojang.com/users/profiles/minecraft/<playername>`
Then, using Visage, we can get a prerendered image of said skin: `GET https://visage.surgeplay.com/full/<uuid>?tilt=[tilt]`

Finally,  uploaded via an embed of some sort, it can be displayed.

**Comment by RealShadowNova** [comment]
I think it'd be nice for a flag called `avatar` so we can select just the head, I've seen a couple bots already do this. That's how I got my pfp.

**Comment by kyranet** [comment]
With Skyra v7's plans, and with the rest of the game integration command removed, I believe we are not longer interested in this.
