### ISSUE TITLE
refactor: remove deprecated Message#deleted accesses

### ISSUE THREAD

**Issue by lveneris** [skyra-project/skyra#2181]
In discordjs/discord.js#7092, `Message#deleted` and the same property on other structures (but we only use the ones for `Message`) were deprecated. There are two accesses for this property, both in [the message utils](https://github.com/skyra-project/skyra/blob/main/src/lib/util/functions/messages.ts#L48-L55).

Initially I'd suggest removing the check and handling it caller-side since the current proposed solutions for checking if a message is deleted or not involve cacheing in a `WeakSet`, but the function is called in many places and that would add *a lot* of code. Therefore, I do not have a good solution to propose, and this issue is just to bring it to attention.

**Comment by favna** [comment]
Yeah I'm aware. I get notified everytime I restart Skyra for an update through the logging. Good to officially list it here though.

**Comment by lveneris** [comment]
> Yeah I'm aware. I get notified everytime I restart Skyra for an update through the logging. Good to officially list it here though.

I knew you would be, but tracking issues are always good. I'm hoping there'll be a good solution without too much boilerplate.

**Comment by kyranet** [comment]
This has been fixed in the v14 rewrite long ago.
