### ISSUE TITLE
bug: events.ban-add and events.ban-remove not creating moderation logs

### ISSUE THREAD

**Issue by SQKo** [skyra-project/skyra#2184]
**Describe the bug**

The event for ban & unban when done by other bots/manual are not posting moderation log.
Bot has enough permission (ban, audit log) for this action.
The configuration setting for `channels.logs.moderation` is enabled.
The configuration setting for `events.ban-add` and `events.ban-remove` are also set to a channel where Skyra can send messages.

**To Reproduce**

1. Ban or Unban someone manually from Discord

**Expected behavior**

It should post the moderation log when I manually ban or unban someone.

**Screenshots**
![Screenshot 2022-02-01 at 22-10-28 Skyra Settings](https://user-images.githubusercontent.com/87897282/152000315-06bdfdeb-80a1-476b-a5a6-b8aec05bd8c3.png)

![Screenshot 2022-02-01 at 22-11-17 Discord - A New Way to Chat with Friends Communities](https://user-images.githubusercontent.com/87897282/152000342-03a2789f-f51f-4065-925c-19968ef43285.png)

![Screenshot 2022-02-01 at 22-10-01 Skyra Settings](https://user-images.githubusercontent.com/87897282/152000393-26a54b21-c7be-4a66-80e5-d7c417c969c1.png)

![Screenshot 2022-02-01 at 22-11-59 Discord - A New Way to Chat with Friends Communities](https://user-images.githubusercontent.com/87897282/152000451-f2e77dcc-22c5-454c-bce7-d09f27c09f79.png)

**Additional context**

It was previously working last time around 09/21/2021
![Screenshot 2022-02-01 at 22-13-42 Discord - A New Way to Chat with Friends Communities](https://user-images.githubusercontent.com/87897282/152000492-0a87214e-3235-40c0-9925-3199945293a5.png)

Support message link: https://discord.com/channels/254360814063058944/382531782387695616/938087109091270697

**Comment by lveneris** [comment]
Update: Found the cause. The `guildBanAdd` event has an object payload that isn't expanded in the function's arguments. By correcting this, I was able to get logs for one ban, but no future bans despite both checks now returning fine. Will continue working.

**Comment by SQKo** [comment]
~~This seems fixed with ban add, but still not working ban remove, can anyone confirm this~~?

Edit: Seems OK now

**Comment by lveneris** [comment]
> ~This seems fixed with ban add, but still not working ban remove, can anyone confirm this~?
> 
> Edit: Seems OK now

I did the testing anyway, works on my end. Glad it's working now.

![image](https://user-images.githubusercontent.com/22531310/153277792-39480a0a-adb4-4dfc-ad36-02d6bacc23c5.png)
