### ISSUE TITLE
bug: warnings not displaying active warnings

### ISSUE THREAD

**Issue by JABirchall** [skyra-project/skyra#2209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

When running the !warnings command with or without a user param, the warnings command always says there are no warnings active.

### Steps To Reproduce

Run following commands

1. s!warn @user test
2. s!case {caseid}
3. s!warnings
4. s!warnings @user

### Expected behavior

Display the active warnings on the server, and per user.

### Screenshots

![](https://i.imgur.com/guovyLZ.png)

### Additional context

The command help text describes this functionality.

**Comment by JABirchall** [comment]
The problem seems to be that the !warnings command code is return mutes, not warnings. 
This contridicts the help text and name of the command leading to confusion as to is function.

**Comment by kyranet** [comment]
This should have been fixed a long time ago, but in case it wasn't, #2595 100% fixed this. Thanks for the issue report!
