### ISSUE TITLE
Help: Show categories instead of commands.

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#320]

**Comment by tech6hutch** [comment]
What's this? Instead of posting a rich embed menu with pages for categories, it would just post a list of all categories, and then users can do the help command again but with the category name they want (as in issue #319)?

**Comment by kyranet** [comment]
I think a flag for listing categories would be ideal, and it'd show this with the page numbers as well.

**Comment by tech6hutch** [comment]
Okay. I think I understand what you want.

Would you prefer all the help command changes (#319, #320, #322; lemme know if I missed any) in one PR or multiple? (Multiple would be better for Hacktoberfest, but I don't mind them being only one.)

**Comment by kyranet** [comment]
If you get all 3 done quickly, I see no harm for making it in a single PR. But feel free to make multiple regardless, gets better to track the changes in the commit list.
