### ISSUE TITLE
Feat(Social): Add more ways to earn money

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#340]

**Comment by favna** [comment]
Wheel of Fortune, based on: https://github.com/Favna/ribbon/blob/master/src/commands/casino/wheeloffortune.ts

**Comment by kyranet** [comment]
Since we're moving to a RPG based system, powered by Nayre, we will not longer require this suggestion to take place. See the [Notion document](https://skyra.notion.site/Skyra-v7-922ba06004654142a7b63347a92513a8) for more information.
