### ISSUE TITLE
Feat(Marry): Allow multiple marriages

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#347]

**Comment by tech6hutch** [comment]
I assume multiple marriages means that users can practice polygamy. This raises a couple questions.

1. Are marriages transitive? i.e., if A marries B, and B marries C, are A and C married?

2. Do a person's existing partner(s) have to approve of any new partner they attempt to marry or divorce? e.g., if A and B are married, and A attempts to marry C, must B agree to it?

**Comment by kyranet** [comment]
You made me aware of how little I know of this world.

1. No, by the logic that a person (A) married with another (B) has a lover (C), A is in relationship with B and C, but B and C only have a relationship with A.

2. No, check point 1.

**Comment by kyranet** [comment]
By the way, you'll have half of this done with #365, I already migrated settings to make marry `string[]` instead of `string | null`.

It will land in a few hours, just for the heads up.
