### ISSUE TITLE
Feat(Starboard): Decrease stars when unreacting

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#349]
#348 should be done before this so people do not spam react/unreact events.

**Comment by superusercode** [comment]
Additionally, it would be cool if unstarred messages get deleted from the star channel. (i.e. message with a single star that the user then removes is removed from the starboard channel)

**Comment by kyranet** [comment]
Since we're removing starboard from Skyra, we will not proceed with the implementation of this feature. See the [Notion document](https://skyra.notion.site/Skyra-v7-922ba06004654142a7b63347a92513a8) for more information.
