### ISSUE TITLE
Settings: Increase Timeout for Settings Menu

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#408]

**Comment by tech6hutch** [comment]
A minute is a decent amount of time tho

**Comment by vladfrangu** [comment]
A minute can also not be enough for slow people who take their sweet time to read, or that don't already know the menu

**Comment by kyranet** [comment]
Or that write a really long paragraph in keys like `mesaages.greeting`.

Currently the timeout is 2 minutes and should be increased to 5 or 10 minutes.

**Comment by vladfrangu** [comment]
Why not make the timeout be configurable per user? Limit it to a max of 20
mins, let's say, and let users set it on their own tastes

**Comment by kyranet** [comment]
Let's just make it 10 minutes, I don't think they really *need* more than that.
