### ISSUE TITLE
Shouldn't reply to @mentions in disabled channels.

### ISSUE THREAD

**Issue by gc** [skyra-project/skyra#436]
If a channel is disabled (so only mods can use commands in it), it should also not reply to @mentions where it replies with `The prefix in this guild is set to: =`.

**Comment by PyroTechniac** [comment]
This requires modification to the default commandHandler monitor

Edit: was just clarifying and giving a point of reference as to where we should start

**Comment by kyranet** [comment]
That'll be necessary, @PyroTechniac 

![image](https://user-images.githubusercontent.com/24852502/67686431-fad22f00-f996-11e9-912e-d8b94989b1a5.png)
