### ISSUE TITLE
Muting someone for negative time causes bad bug

### ISSUE THREAD

**Issue by gc** [skyra-project/skyra#440]
E.g. `=mute @Kyra -1s buggy code` 

Skyra replies with an error, the person is muted, but nothing is logged, so not sure if it's an actual mute or what, but yea

**Comment by kyranet** [comment]
Fixed in 403dc1f, will close once the moderation rework lands.

**Comment by gc** [comment]
I'm not sure the cause here, but probably a good idea to check every other command handles negative numbers okay as well. Perhaps the Arg/usage could fix it

**Comment by kyranet** [comment]
You're right, I wasn't taking negative durations in the `timespan` argument. Fixed in 6dff856, which has been cherrypicked to production and deployed.
