### ISSUE TITLE
Customizing punishment responses

### ISSUE THREAD

**Issue by gc** [skyra-project/skyra#473]
I want to be able to not show the reason for the punishment in skyras response.

Also, it would be nice if its possible to customize the responses completely - but this probably will need thought put into it, for example i think the best possible way to implement it is in the dashboard with variables, e.g. I could customize my mute response by typing this into a text input on the dashboard: `{user} was muted for {duration}.`. But then theres also the dm sent to the user, and the unmute command. its complex, i dont know how it should be done or if it should be done. If its just going to be stupidly complex/annoying then its not worth it

**Comment by kyranet** [comment]
We will use ephemeral messages for moderation messages starting with Skyra v7, so this is not longer needed nor worth it. You can check our [Notion document](https://skyra.notion.site/Skyra-v7-922ba06004654142a7b63347a92513a8) to read more on our future changes.
