### ISSUE TITLE
A couple bugs

### ISSUE THREAD

**Issue by gc** [skyra-project/skyra#500]
1. `s!price btc usd 1000` - should say `1000 btc is {value} usd`, but instead it basically says that 1 btc is the price of 1000 btc
![image](https://user-images.githubusercontent.com/30398469/68642495-71a82400-0562-11ea-9e69-43ee7bcc9f8e.png)

2. If you do `=pay 200 @someone`, and then gamble away so you have less than 200, then click `yes` to proceed with the `pay`, skyra prints a terrible failure. (they dont receive the extra money though, so not really a big bug)

**Comment by kyranet** [comment]
Fixed in 39de6c1 and 69ca2f3
