### ISSUE TITLE
request: coinflip

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#522]
**Is your feature request related to a problem? Please describe.**
I swear I remember having added this command two years ago. Turns out, I never did.

**Describe the solution you'd like**
Implement the coinflip command.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by cfanoulis** [comment]
claiming this (and actually doing it)

**Comment by favna** [comment]
@cfanoulis I had this in Ribbon so if you need a hand: https://github.com/Favna/ribbon/blob/master/src/commands/games/dndcoin.ts

![](https://storage.googleapis.com/data-sunlight-146313.appspot.com/ribbon/dndheads.png)
![](https://storage.googleapis.com/data-sunlight-146313.appspot.com/ribbon/dndtails.png)

The images I used

**Comment by cfanoulis** [comment]
@Favna thanks :)
