### ISSUE TITLE
Biggify command

### ISSUE THREAD

**Issue by gc** [skyra-project/skyra#533]
Ordos implementation using JIMP

```js
const { url } = await msg.channel.fetchImage();
const img = await jimp.read(url);
img.resize(400, jimp.AUTO);
const chunkHeight = img.bitmap.height / 4;
for (let i = 0; i <= 3; i++) {
	const tempImg = img.clone().crop(0, chunkHeight * i, 400, chunkHeight);
	await new Promise((resolve, reject) => {
		tempImg.getBuffer('image/png', (err, buffer) => err ?
			reject(err) :
			resolve(msg.channel.sendFile(buffer, 'image.png')));
	});
}
```

![image](https://user-images.githubusercontent.com/30398469/69006645-16bd6500-0986-11ea-9bb8-de5a34ec9225.png)

![image](https://user-images.githubusercontent.com/30398469/69006647-1c1aaf80-0986-11ea-9bfd-c53514117b3f.png)

make sure to account for very small images/very big images and wacky aspect ratios.

**Comment by kyranet** [comment]
Skyra will not have this command, Teryl (tools) would have too many commands with this, and it's not fun enough to fit in Artiel. Furthermore, there are concerns such as expanding  content  we're not allowed to, such as commissioned art.

You can check the future changes in our [Notion document](https://skyra.notion.site/Skyra-v7-922ba06004654142a7b63347a92513a8).
