### ISSUE TITLE
randquote command

### ISSUE THREAD

**Issue by gc** [skyra-project/skyra#536]
ordos implementation:
```js
let messageBank = await msg.channel.messages.fetch({ limit: 100 });

for (let i = 0; i < 6; i++) {
    const fetchedMessages = await msg.channel.messages.fetch({ limit: 100, before: messageBank.last().id });
    messageBank = messageBank.concat(fetchedMessages);
}

for (let i = 0; i < messageBank.size; i++) {
    const message = messageBank.random();
    if (message.author.bot) continue;
    if (message.content.replace(/\W/g, '').replace(/[0-9]/g, '').length < 20) continue;

    const embed = new MessageEmbed()
        .setDescription(message.content)
        .setAuthor(message.author.username, message.author.avatarURL());
    return msg.send({ embed });
}
return msg.send(`Couldn't find a quote.`);
```

My implementation ignores bots (not often very interesting, just random bot messages), and ignores messages which arent likely to be normal conversational messsages, e.g. tries to ignore stuff like a command thats just an emoji or a command.

`msg.channel` should probably get an extendable to do the messagebank thing as markov does the exact same thing.

**Comment by favna** [comment]
As a message flag we could provide `--img` / `--image` in which case it would filter for only messages that have images. This is based on some talk I had with a friend who had this in his bot.

**Comment by kyranet** [comment]
This command would naturally move to Artiel (fun bot) since it's not an utility (Teryl) and also not part of moderation (Skyra), however, Artiel has no access to messages, so this is not doable. Please check the [Notion document](https://skyra.notion.site/Skyra-v7-922ba06004654142a7b63347a92513a8) for more information.
