### ISSUE TITLE
bug: Star command is not giving a random entry on PGSQL

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#544]
**Describe the bug**
https://github.com/kyranet/Skyra/blob/7f21f1c13924abb5277a37608704649c6bf113d3/src/lib/queries/postgres.ts#L182-L194

The SQL query does not sort the entries by random

**To Reproduce**
Write s!star
Write s!star
Both messages are the same

**Expected behavior**
Both messages are (ideally) random

**Screenshots**
On a server with +800 starboard entries:
![image](https://user-images.githubusercontent.com/24852502/69015629-188f2480-0996-11ea-9bba-2b4a16489dc1.png)

**Additional context**
None.

**Comment by PyroTechniac** [comment]
Is the behavior also found with the JSON provider?

**Comment by kyranet** [comment]
No, just PGSQL as the title describes.

**Comment by PyroTechniac** [comment]
Hmm, odd. A potential fix would possibly to be excluding the previous messageID from the query? But that would cause extra complications with how to pass it and how it's stored.

**Comment by kyranet** [comment]
No, the correct way to do it is in [here](https://lmgtfy.com/?q=pick+random+element+from+table+postgres)
