### ISSUE TITLE
request: adjust the amount of info put on starboard cards

### ISSUE THREAD

**Issue by ghost** [skyra-project/skyra#567]
**Is your feature request related to a problem? Please describe.**
currently stars look like this:
![image](https://user-images.githubusercontent.com/7173984/69472174-c292f600-0d74-11ea-94b5-4783e68a4771.png)
the starboard bot i use currently ([hoshi](https://github.com/1Computer1/hoshi), open source):
![image](https://user-images.githubusercontent.com/7173984/69472181-dc343d80-0d74-11ea-8478-f7d3c8c8646f.png)
![image](https://user-images.githubusercontent.com/7173984/69472219-359c6c80-0d75-11ea-95ba-67750335a81d.png)

**Describe the solution you'd like**
ID is not repeated twice and star info is kept at the bottom of the card, better media and pfp embeds where possible.

**Describe alternatives you've considered**
I've just kept hoshi in my server for the time being, but the ban on self starring is really starting to annoy people.

**Additional context**

**Comment by kyranet** [comment]
You're looking at a very old version of Skyra's starboard as you can see in the date, the new version is far better, includes jump to link, and doesn't show IDs anymore.

**Comment by kyranet** [comment]
For reference, this is how they look like:

(Disregard the reactions, that's another bot reacting automatically).

![Screenshot_2019-11-23-08-13-26-352_com discord](https://user-images.githubusercontent.com/24852502/69475112-6d350400-0dc9-11ea-98a3-f58c820004a9.jpg)

---

Regardless of that, your other suggestion (ban of self-starring) flags a feature from Skyra as opinionated, and you're right. Through a little rework I can make a setting to allow them :+1:

Do you want to open an issue to track said setting?

**Comment by ghost** [comment]
I'll make a new issue for that, thanks!

**Comment by kyranet** [comment]
Alright, thanks you very much for reminding me of this, I'll look into fixing it for next week maximum :)
