### ISSUE TITLE
feature: discoin intergration

### ISSUE THREAD

**Issue by cfanoulis** [skyra-project/skyra#609]
Add [Discoin](https://discoin.gitbook.io/) integration

The **PROS**
 - A novel idea for skyra
 - Helps cooperate with other bots
 - Free ad, kinda?

The **CONS**
 - Maybe economic inflation

~~Blocked until @austinhuang0131 accepts skyra in the system~~ See below

Assigned-to: @cfanoulis

**Comment by kyranet** [comment]
Assigning to @QuantumlyTangled. We need analytics on Skyra's own social system so we can track winrates, money lose, money earn, etc.

And furthermore, the commands that are most used in periods of time, so we can see which ones are used the most, which ones have higher winrates, and which ones have lower winrates.

**Comment by cfanoulis** [comment]
pinging @austinhuang0131 so that he is updated about the status on this

**Comment by austinhuang0131** [comment]
I am not blocking it, also subscribed

**Comment by cfanoulis** [comment]
~~status update: skyra is ok to join as per @austinhuang0131, so we're waiting on:
a. Quantum to deploy statistics
b. my ass to implement this feature~~

waiting on approval

**Comment by favna** [comment]
I personally think we should not do this. In short, I personally think Skyra should stay and be Skyra and not cater to the 0.1% who want to use Skyra along with other bots to the extend of sharing currency between them.

Furthermore I personally consider any crypto that is not something popular like Litecoin / Eth / BTC / XML / etc basically a memecrypto that should never been taken serious ¯\_(ツ)_/¯

**Comment by austinhuang0131** [comment]
*Warning: owner bias*

It might be 0.1% currently but it could add up in the future. Discoin is also not designed to *replace* but to *supplement* a bot's economy, as we require bots to have native earning/spending methods.

Furthermore this is not a crypto, it simply calculates the amount of money to be received on the other bot for it to be picked up, it is not meant to be serious yet it could be helpful for some... Plus it has been there for 2 years

**Comment by gc** [comment]
Not a fan

**Comment by PyroTechniac** [comment]
Unless this service suddenly blows up within the Discord botting community, I feel like this should go 2 ways
1. We just leave it alone and don't worry about it or
2. It gets put on the back burner, either making it the last to release for this version or not released until next version even.

**Comment by cfanoulis** [comment]
Since we have a majority **against** adding this, with a 3+1 against versus 1 for, this suggestion falls through and **will not be added**

Thanks all for participating
