### ISSUE TITLE
bug: prune command bug

### ISSUE THREAD

**Issue by gc** [skyra-project/skyra#620]
![70148612-9bd0aa00-16fa-11ea-979e-57c7df3044d6](https://user-images.githubusercontent.com/30398469/70148861-1994b580-16fb-11ea-9ef4-fd8a804a158b.png)

**Comment by favna** [comment]
What is the expected result?

**Comment by kyranet** [comment]
The expected behaviour is filter being *before* the new arguments (position and target).

That way when you use a filter, the other two don't trigger, plus they're very optional to be fair.
