### ISSUE TITLE
Feat(GI): osu! Commands.

### ISSUE THREAD

**Issue by Quantumlyy** [skyra-project/skyra#629]
`#203` in `#suggestions`.
`#208` in `#suggestions`.

**Comment by favna** [comment]
See https://github.com/Favna/ribbon/blob/master/src/commands/leaderboards/osu.ts

**Comment by vladfrangu** [comment]
It's called `osu!` not `OSU!`. 😠 

And to actually be helpful - API v2 is a thing that's coming eventually!

**Comment by favna** [comment]
Closing as this is not a feature we will be chasing anymore
