### ISSUE TITLE
Feat(GI): Roblox Commands.

### ISSUE THREAD

**Issue by Quantumlyy** [skyra-project/skyra#647]
`#208` in `#suggestions`.

**Comment by Favna** [comment]
ew /s

**Comment by Quantumlyy** [comment]
~~https://developer.roblox.com/en-us/api-reference~~ 

Moderator edit: this link goes to the API for adding to the Roblox game, not user statistics.

**Comment by favna** [comment]
Roblox has an API now that can be used:

Users: https://users.roblox.com/docs
Groups: https://groups.roblox.com/docs#!/v1 (v2 is still in development)
API: https://api.roblox.com/docs

There is APIs that handle Discord users to Roblox users aswell
https://verify.eryn.io/api and https://blox.link/developers

There is a huge list https://devforum.roblox.com/t/collected-list-of-apis/557091


Information provided by GoldenAngel#6734 (416735346202640406) (https://discord.com/channels/254360814063058944/262740083977879552/858719659125637172)

**Comment by favna** [comment]
Closing as this is not a feature we will be chasing anymore
