### ISSUE TITLE
bug: Cant manage guild even though has admin role

### ISSUE THREAD

**Issue by gc** [skyra-project/skyra#653]
Relevant code: https://github.com/kyranet/Skyra/blob/master/src/routes/oauth/oauthUser.ts#L160

If a user has the configured admin role, but no discord perms/manage server at all, `manageable` should still be true.

**Comment by kyranet** [comment]
https://github.com/kyranet/Skyra/blob/4f5f0419399c3e70d70a5257d903902b228167a0/src/routes/oauth/oauthUser.ts#L170

**Comment by kyranet** [comment]
Fixed in #993.
