### ISSUE TITLE
bug: banner list -> all shows "undefined" shinies

### ISSUE THREAD

**Issue by favna** [skyra-project/skyra#661]
**Describe the bug**

**To Reproduce**
1. Write '!sbanner list'
2. Write 'all'
3. See embed shows "undefined [shiny emote]"

**Expected behavior**

Shiny price for a banner is shown

**Screenshots**

![image](https://user-images.githubusercontent.com/4019718/70847657-0b673780-1e67-11ea-85cd-c8d433714735.png)

**Comment by cfanoulis** [comment]
kinda assigned to me
