### ISSUE TITLE
Feat(GI): League of Legends Commands.

### ISSUE THREAD

**Issue by Quantumlyy** [skyra-project/skyra#681]
`#208` in `#suggestions`.

**Comment by Quantumlyy** [comment]
https://developer.riotgames.com/apis

**Comment by CyberiumShadow** [comment]
What kind of output do you want here? 
Rich Embed with account data etc or just text responses?

Any aversion to using already existing league api libraries or would you rather a new one created for this

**Comment by Quantumlyy** [comment]
> What kind of output do you want here? 
> Rich Embed with account data etc or just text responses?
> 
> Any aversion to using already existing league api libraries or would you rather a new one created for this

In regards to output, I'd say that account data in an Embed seems good.
But as for the library I think its safe to say that just wrapping endpoints with the fetch function seems fine as thats how the other GI commands do it.

**Comment by favna** [comment]
We don't really use libraries for APIs in Skyra's codebase and instead make our own fetch calls. Also for the same reason, commands like this should always return Rich Embeds.

As for what content it should return, that's either up to @QuantumlyTangled to say or if someone who actively plays LoL can say what they would want from such a command within the context of Discord messages that would be helpful as well.

**Comment by favna** [comment]
Closing as this is not a feature we will be chasing anymore
