### ISSUE TITLE
request: Music enhancements

### ISSUE THREAD

**Issue by gc** [skyra-project/skyra#691]
1. Ability to promote songs to the front of the queue (DJ only). On dashboard it will be a button, skyra command would maybe be `s!promote <song_index|song_id|song_name/url>`
2. Show the Queue in an embed with rich menu, will make the queue msg 2x smaller/shorter
![image](https://user-images.githubusercontent.com/30398469/71474234-a16b6c80-282e-11ea-9ecc-d70889473c43.png)
3. Show the music dashboard link when you show the queue or add the first song to the queue

**Comment by cfanoulis** [comment]
2 has been done in #695

**Comment by favna** [comment]
1 and 3 are pending respectively in #1081 and #1084
