### ISSUE TITLE
request: Suggestions module

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#709]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**

Add the keys:

- `suggestions.on-action.dm`: Whether or not Skyra should send a DM when the status of one suggestion is changed.
- `suggestions.on-action.repost`: Whether Skyra should edit the original message, adding a field to it, or send a different one.
- `suggestions.on-action.display-author`: Whether Skyra should display the user who took the action on the suggestion request.
- `suggestions.channel`: The channel where suggestions will be posted.
- `suggestions.emojis.upvote`: The emoji used for upvote, defaults to ⏫.
- `suggestions.emojis.downvote`: The emoji used for downvote, defaults to ⏬.

> **Note**: Emojis will eventually get a custom one, those are temporary.

Add the commands:

- `s!suggest <content:string{2000}>`
- `s!resolve-suggestion <accepted|considered|denied> <id:snowflake> [message:string{2000}]`, optionally `--hide-author` and `--display-author` flags to override `suggestions.on-action.display-author`.

**Describe alternatives you've considered**
N/a.

**Additional context**
N/a.

**Comment by cfanoulis** [comment]
assign me please

**Comment by cfanoulis** [comment]
estimated time to land: 24hrs
