### ISSUE TITLE
core: Switch to monorepo

### ISSUE THREAD

**Issue by kyranet** [skyra-project/skyra#710]
**Is your feature request related to a problem? Please describe.**
Yes, the organisation of the current code will be bad for embedding other components.

**Describe the solution you'd like**
Once the current PRs finalize, I would like to move everything related to Skyra to a separate folder, so other micro-services that are made specifically for Skyra can be included in the same repository, even if they're in different languages (hs-gateway, ryana...).

**Describe alternatives you've considered**
I considered many alternatives but none got convincing enough to be worth mentioned.

**Additional context**
N/a.

**Comment by cfanoulis** [comment]
I suppose a top-level yarn workspace and then separate folders for
 - skyra
 - ryana
 - whatever
 - docker files to run everything

with each folder having its package manager manifest?

**Comment by favna** [comment]
suggestion:

<details><summary>As text</summary>

<p>

```
.
├── assets
│   ├── fonts
│   │   ├── Family-Friends.ttf
│   │   ├── NotoEmoji.ttf
│   │   ├── NotoSans-Regular.ttf
│   │   ├── Roboto-Light.ttf
│   │   └── Roboto-Regular.ttf
│   ├── github
│   │   ├── bitcoin.png
│   │   ├── ethereum.png
│   │   ├── litecoin.png
│   │   └── patreon.png
│   ├── images
│   │   ├── memes
│   │   │   ├── ChangeMyMind.png
│   │   │   ├── chase.png
│   │   │   ├── cuddle.png
│   │   │   ├── DeletThis.png
│   │   │   ├── f.png
│   │   │   ├── goodnight.png
│   │   │   ├── goofy.png
│   │   │   ├── howtoflirt.png
│   │   │   ├── hug.png
│   │   │   ├── imageSlap.png
│   │   │   ├── ineedhealing.png
│   │   │   ├── Shindeiru.png
│   │   │   ├── TheSearch.png
│   │   │   └── triggered.png
│   │   ├── social
│   │   │   ├── shiny-icon.png
│   │   │   ├── sm-icons.png
│   │   │   ├── wof-arrows.png
│   │   │   ├── wof-lose-icons.png
│   │   │   └── wof-win-icons.png
│   │   └── weather
│   │       ├── dark
│   │       └── light
│   └── public
│       └── img
│           ├── badges
│           ├── banners
│           ├── coins
│           ├── icons
│           ├── pokemon
│           ├── Skyra.png
│           ├── SkyraTitleDark.png
│           └── SkyraTitleLight.png
├── LICENSE
├── package.json
├── README.md
├── services
│   ├── docker
│   │   ├── bash-skyra.sh
│   │   ├── docker-compose.yml
│   │   ├── influxdb
│   │   │   ├── config.sample.toml
│   │   │   ├── config.toml
│   │   │   └── Dockerfile
│   │   ├── lavalink
│   │   │   ├── application.example.yml
│   │   │   ├── application.yml
│   │   │   ├── Dockerfile
│   │   │   ├── Lavalink.jar
│   │   │   └── README.md
│   │   ├── ps-skyra.ps1
│   │   └── README.md
│   ├── ryana
│   └── skyra
│       ├── bwd
│       │   └── providers
│       ├── changelogs
│       │   ├── 3.0.0 Royal.diff
│       │   ├── 3.2.0 Ny-Royal.diff
│       │   ├── 3.3.0 Ny-Royal.diff
│       │   ├── 3.4.0 Ny-Royal.diff
│       │   ├── 4.0.0 Nerom.diff
│       │   └── 5.0.0 Nerom v2.md
│       ├── config.example.ts
│       ├── config.ts
│       ├── database
│       │   ├── 5.0.0.ts
│       │   ├── 5.1.1.ts
│       │   ├── 5.2.0.ts
│       │   ├── 5.2.1.ts
│       │   └── 5.3.0.ts
│       ├── package.json
│       ├── README.md
│       ├── src
│       │   ├── arguments
│       │   ├── commands
│       │   ├── events
│       │   ├── extendables
│       │   ├── finalizers
│       │   ├── inhibitors
│       │   ├── ipcMonitors
│       │   ├── languages
│       │   ├── lib
│       │   ├── middlewares
│       │   ├── monitors
│       │   ├── providers
│       │   ├── routes
│       │   ├── serializers
│       │   ├── Skyra.ts
│       │   └── tasks
│       └── tsconfig.json
└── yarn.lock
```

</p>
</details>

<details><summary>As image with colours</summary>
<img src="https://user-images.githubusercontent.com/4019718/71645685-665cb380-2cdc-11ea-9a55-b1575675dfaf.png"/>
</details>

**Comment by Tylertron1998** [comment]
imo, monorepos are never a good idea. If I'm working on Ryana, and you're working on skyra, and then I push but then you push, we're going to get git errors and all kinds of bad memes. It also increases the download time and gives stuff that a certain developer might not want (I don't care about skyra core when I'm working on ryana)

**Comment by favna** [comment]
> we're going to get git errors and all kinds of bad memes

Since the commits in question aren't modifying the same files this *should* not happen. Furthermore since we have a locked master branch and always work through pull-requests the actual conflicts are fixed on a branch and github does a squash and rebase when merging.

> it also increases the download time and gives stuff that a certain developer might not want

Very valid point. Though Git has tried to make this process better with solutions such as Git LFS (for large artifacts), Git Clone --shallow (for less history) and sparse checkout, none of these solutions are really developer-friendly, possible in most GUI apps nor easy to manage.

**Comment by kyranet** [comment]
> it also increases the download time and gives stuff that a certain developer might not want

You're right, I think we should definitely keep LyCore separated and close this issue.
