### ISSUE TITLE
request: Nitro boost incentives

### ISSUE THREAD

**Issue by gc** [skyra-project/skyra#786]
- Every server wants boosters, and wants to keep their boosters
- Giving perks to boosters is the best way of getting/keeping boosters
- If Skyra could help servers provide perks for boosters, and every server wants boosters....

I'm suggesting a modular system for providing perks/incentives to nitro boosters.

For example: a configurable amount of emojis that boosters can manage through the bot - you could tell skyra that you want boosters to be able to manage 2 emote slots, then they can `s!nitro emoji <upload_image>` or something like that. So basically, skyra lets them manage only 2 emote slots through her. When they stop boosting, the emojis are deleted.

Things to consider:  users can boost a server twice, boosts run out, admins can boost (so they should bypass some perks, e.g. the emoji idea)

**Comment by kyranet** [comment]
This has been made possible thanks to [`discord/discord-api-docs#1537`](https://github.com/discord/discord-api-docs/issues/1537), but we might need to wait for `@klasa/core` migration as discord.js does not support it yet.

**Comment by kyranet** [comment]
We'll stick with skyra-project/teryl#10 which is less specific. I personally can't think of more incentives, and even so, we can implement commands to manage those separately.
