### ISSUE TITLE
request: Export song queue

### ISSUE THREAD

**Issue by cfanoulis** [skyra-project/skyra#852]
**Is your feature request related to a problem? Please describe.**
Cannot export the currently playing queue

**Describe the solution you'd like**

A command to export the currently playing queue, as guildid-timestamp.skyraqueue file. Contents encoded with binarytf.

**Describe alternatives you've considered**

Manually keeping track... wasn't fun

**Additional context**

- `;;export` in fredboat
- ???

**Comment by favna** [comment]
Idea is good, it would also be nice if it could be exported to hasteb.in just like how eval can upload there. So some flags would be `--output-to=hastebin` / `--output-to=file` and `--hastebin` and `--file` respectively. With file always being the default.

**Comment by Quantumlyy** [comment]
Please do explain the data structure. @cfanoulis

**Comment by MrJacz** [comment]
@QuantumlyTangled array of Base64 lavalink track strings of dump the entire queue in loadtracks format

**Comment by cfanoulis** [comment]
> Please do explain the data structure. @cfanoulis
@QuantumlyTangled something like...
```js
{
    v: 1 // Version number, in case you want to edit format?
    s: [
        {
            req: 00000 // user id of the person that requested this
            yt: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'
        },
        {
            req: 00000 // user id of the person that requested this
            yt: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'
        }
    ]
}
```

obviously, without the comments

**Comment by kyranet** [comment]
I fail to see the point on storing the user IDs, kinda feels like a privacy issue (specially if they get leaked). Besides, if imported, the one who added those entries was the user itself.

Also this way we can import songs from a pre-defined queue and still get checked correctly when adding (remember, Skyra has a configurable limit for how many songs you can add).

Additionally, I think we could also add something so people can add a portion of it, defining offset and amount via either arguments or flags.

**Comment by cfanoulis** [comment]
Current sample form:
```
{"v":1,"q":["https://www.youtube.com/watch?v=LaX858gifDs","https://www.youtube.com/watch?v=bW9Oz7XIvFc"]}
```

**Comment by favna** [comment]
We can shorten the URLs with` youtu.be` URL. 

`https://youtu.be/<VideoID>`

Saves on data to send etc etc

**Comment by MrJacz** [comment]
I don't see the need to store the urls?
Skyra uses lavalink, so if you just store the Lavalink track ids thats all you need
Then you can just resolve the track using the resolvetracks api or just make the lavalink track resolver in javascript (not hard been done before just a lot of binary/buffer stuff) i'll try to find a package if u mention me in discord.
@kyranet if you remember when I asked if u could setup a haste server for skyra this is what I was gonna do

Edit: also there is no need at all for user ids. the true requested user would be the user who played the dump url not who put the song into that list.

another example of a dump command is
pengubot's implementation, dabbot and that is all that i can think of

**Comment by cfanoulis** [comment]
Aren't the trackIDs specific to this session only? or are they the video
ids?

**Comment by cfanoulis** [comment]
In addition, @kyranet has denied hosting a hastebin server.

**Comment by cfanoulis** [comment]
thank you Gmail for royally fucking up!


Aren't track IDs session-specific? Or are they the video IDs. Also, you can load music from sources other than YT.

In addition, @kyranet has denied hosting a hastebin server

**Comment by favna** [comment]
Cleaned up duplicate comments to fix Gmail's royal fuck up. 

p.s.: disable github email notifs and get an app smh

**Comment by MrJacz** [comment]
@cfanoulis the track id's are literally the track json in a binary form.
Just look at this [@lavalibs/encoding](https://github.com/lavalibs/encoding).
So no they arent session specific
