### ISSUE TITLE
bug: Playing message is sent twice

### ISSUE THREAD

**Issue by cfanoulis** [skyra-project/skyra#921]
**Describe the bug**
The playing message is sent twice when the queue starts

**To Reproduce**
 - Add a song with `s!add` (Idk if this affects reproducibility)
 - Use `s!play`
 - O b s e r v e

**Expected behaviour**
Skyra sends 1 playing notification

**Screenshots**
![bug screenshot](https://user-images.githubusercontent.com/38255093/79308800-ec0a1500-7f01-11ea-8e7f-625bfa9d92a7.png)

**Additional context**
NaN

**Comment by favna** [comment]
![image](https://user-images.githubusercontent.com/4019718/79308983-d264cf80-7ef9-11ea-8aba-10801f6ae18b.png)

Verification of bug, can reproduce.
